POST http://localhost:7071/api/helloFunction
content-type: application/json

{
  "Foobar": "Lemon curd"
}

###########################################

GET http://localhost:7071/api/helloFunction

###########################################

GET http://localhost:7071/api/fractalFunction